### ISSUE TITLE
Missing examples for how to use options

### ISSUE THREAD

**Issue by charleystran** [amberframework/jasper-helpers#40]
I am trying to do what I think is pretty basic, but there are no examples in the readme to go off. 

What I am trying to accomplish is creating a password field. This is what I am trying:

`<%=` text_field(name: "password", options: { type: "password" }) %>`

but I am getting this error:

`Error: no overload matches 'Hash(Symbol, Array(Int32 | String) | Array(Int32) | Array(String) | Bool | Float32 | Float64 | Int16 | Int32 | Int64 | Int8 | Slice(UInt8) | String | Symbol | Time | Nil)#[]=' with types Symbol, NamedTuple(type: String)`

Can you provide an example of how to properly use the options hash?

**Comment by crimson-knight** [comment]
I know this issue is a few years old, but for anyone else who comes across this, the issue here is the syntax. The `options: { type: "password" }` here defines a `NamedTuple` not a `Hash`.

The correct syntax would be `<%= text_field(name: "password", type: "password") %>` and this will render a password text field. The `options` hash is a double-splatted hash which means all of the unnamed parameters will get turned into a hash. So you can use this to add data attributes or any other attributes you would like! :)
